name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
      - uses: actions/checkout@v2
      - run: node -v
      - run: npm -v
      - run: yarn -v
      - run: npm ci --include=dev
      - run: npx eslint .
      - run: npm test
        env:
          CI: true
          DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
          LL_HOST: ${{ secrets.LL_HOST }}
          LL_PORT: ${{ secrets.LL_PORT }}
          LL_PASSWORD: ${{ secrets.LL_PASSWORD }}
          LL_SECURE: ${{ secrets.LL_SECURE }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
